-- AlterTable (idempotent)
ALTER TABLE "Variant" ADD COLUMN IF NOT EXISTS "weight" DOUBLE PRECISION;
ALTER TABLE "Variant" ADD COLUMN IF NOT EXISTS "weightUnit" TEXT;
ALTER TABLE "Variant" ADD COLUMN IF NOT EXISTS "requiresShipping" BOOLEAN;
ALTER TABLE "Variant" ADD COLUMN IF NOT EXISTS "taxable" BOOLEAN;
ALTER TABLE "Variant" ADD COLUMN IF NOT EXISTS "inventoryPolicy" TEXT;
ALTER TABLE "Variant" ADD COLUMN IF NOT EXISTS "inventoryQuantity" INTEGER;
ALTER TABLE "Variant" ADD COLUMN IF NOT EXISTS "shopifyUpdatedAt" TIMESTAMP(3);
